blank_issues_enabled: false
contact_links:
  - name: 📚 Teacher Documentation
    url: https://github.com/LeatherBrawler/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn more about how the website works and development process
  - name: 💬 General Discussion
    url: https://github.com/LeatherBrawler/skills-expand-your-team-with-copilot/discussions
    about: Ask questions, share ideas, or discuss the website with other teachers
  - name: 🚀 GitHub Copilot Help
    url: https://docs.github.com/en/copilot
    about: Learn more about GitHub Copilot and how it helps with coding tasks